const modelOrder = {
  id: "4412690235532",
  number: "1371",
  marketPlaceId: null,
  groupId: null,
  name: "#1371",
  packsId: null,
  email: null,
  fulfillmentStatus: {
    id: null,
    status: null,
    ecartapi: "unfulfilled",
    ecartapiId: "3",
    partiallAvailable: "true",
  },
  currency: "MXN",
  totals: {
    subtotal: "240.00",
    total: "340.00",
    tax: "100.00",
    discount: "10.00",
    weight: "0.30",
    shipping: "0.00",
  },
  taxesIncluded: "false",
  taxLines: [],
  units: { weight: "kg" },
  status: {
    id: null,
    status: "any",
    financial: "paid",
    ecartapi: "paid",
    ecartapiId: "1",
  },
  locationId: null,
  reference: null,
  tags: Array(1)["imported"],
  payment: { method: null, status: "paid", ecartapi: null },
  customer: {},
  refunds: [],
  billingAddress: {
    id: null,
    firstName: "Alex",
    lastName: "de la Cruz",
    dni: null,
    identificationNumber: null,
    address1: "123 Fake Street",
    address2: null,
    address3: null,
    country: { code: "CA", name: "Canada", codeIso2: null, codeIso3: null },
    state: { code: "ON", name: "Ontario", codeIso2: null, codeIso3: null },
    city: "Fakecity",
    postalCode: "K2P 1L4",
    phone: "555-555-5555",
    email: null,
    company: "envia.com",
    references: null,
  },
  logistic: { mode: null, type: null, free: "false", direction: null },
  shippingMethod: null,
  shippingOptionReference: null,
  shippingLabel: null,
  shippingAddress: {
    id: null,
    firstName: "John",
    lastName: "Silver",
    dni: null,
    identificationNumber: null,
    address1: "123 Fake Street",
    address2: null,
    address3: null,
    country: { code: "CA", name: "Canada", codeIso2: null, codeIso3: null },
    state: { code: "ON", name: "Ontario", codeIso2: null, codeIso3: null },
    city: "Fakecity",
    postalCode: "K2P 1L4",
    phone: "555-555-5555",
    email: null,
    company: "envia.com",
    references: null,
  },
  items:
    Array(1)[
      {
        id: "11690079682700",
        variantId: "33732617797772",
        productId: "4591541944460",
        offerId: null,
        inventoryId: null,
        sku: "TEST1",
        fulfillment: { quantity: "1", service: "manual", status: null },
        name: "Camisa manga larga - M",
        upc: null,
        requiresShipping: "true",
        quantity: "1",
        currentQuantity: null,
        price: "250.00",
        discount: "10.00",
        associatedItems: [],
        bundled: "false",
        tax: null,
        taxable: "false",
        weight: "0.20",
        vendor: "ecarttest",
        imageUrl: null,
        ecartapiUrl:
          "https://eshop-deve.herokuapp.com/api/v2/products/4591541944460",
      }
    ],
  packages: [],
  meta: null,
  dates: {
    deliveredAt: null,
    canceledAt: null,
    closedAt: null,
    createdAt: "2023-03-02T13:33:11-05:00",
    updatedAt: "2023-03-02T13:33:12-05:00",
    paidAt: "2023-03-02T13:33:11-05:00",
  },
  cancelReason: null,
  note: null,
  locations: [],
  localizationExtensions: [],
  checkoutId: null,
};
export { modelOrder };
